###register request

POST http://localhost:8000/auth/register
Content-Type:application/json

{
 "user_name":"zahrasd",
 "email":"zahrast@google.com",
 "mobile":"09363096180",
 "password":"123456",
 "confirm_password":"123456"


}