###  create team
POST http://localhost:8000/team/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


{
    "name":"zaraa",
    "description":"about programmin back end",
    "user_name":"zizi"
}


### get list team

http://localhost:8000/team/list
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


### get team by id
GET  http://localhost:8000/team/631c4aea4ccb2b69e6013077
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### get my team
GET  http://localhost:8000/team/me
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


###remove team by id
DELETE   http://localhost:8000/team/remove/631c4aea4ccb2b69e6013077
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


###invite user to team
GET    http://localhost:8000/team/invite/6319c09bea47b0a4e431d661/zahra
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json