### request getprofile
GET  http://localhost:8000/user/profile
Authorization: Bearer {{$dotenv token}}


###edit user profile
POST   http://localhost:8000/user/profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{

    "frist_name":"Zahra",
    "last_name":"Sadati",
    "skills":["programmer","nodejs","backend"]
}

### get all request for user
GET    http://localhost:8000/user/requests
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


### get  request by status
GET    http://localhost:8000/user/requests/pending
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json
